# Poetry
[project]
name = "urban-heatmap"
version = "0.1.0"
description = "Map temperature variation across city areas to show heat islands."
authors = [
    {name = "afredoherculano",email = "alfredoherculano@proton.me"}
]
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.139.2,<0.140.0)",
    "uvicorn (>=0.51.0,<0.52.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


# Ruff
[tool.ruff]
src = ["backend"]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "N", # pep8-naming
    "UP" # pyupgrade
]
ignore = ["E501"]  # Line too long (handled by formatter)

[tool.ruff.format]
quote-style = "double"
indent-style = "space" # default = 4 spaces
[dependency-groups]
dev = [
    "pre-commit (>=4.6.1,<5.0.0)"
]
